// extension/ui/src/components/EditModeExtensionsTab.tsx
/**
 * EditModeExtensionsTab - Tab content for Fleet extensions management in edit mode.
 *
 * Shows:
 * - List of installed Fleet extensions with their status
 * - List of Fleet extension images (built but not installed)
 * - Which extension currently owns/controls Fleet
 * - Actions to take control if applicable
 *
 * This is displayed as a tab within the EditModePanel, providing a user-friendly
 * view of the extension ownership mechanism for users working on custom extensions.
 */

import { useState, useEffect, useCallback, useMemo } from 'react';
import { alpha } from '@mui/material/styles';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Chip from '@mui/material/Chip';
import IconButton from '@mui/material/IconButton';
import Button from '@mui/material/Button';
import Tooltip from '@mui/material/Tooltip';
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemIcon from '@mui/material/ListItemIcon';
import ListItemText from '@mui/material/ListItemText';
import Radio from '@mui/material/Radio';
import RefreshIcon from '@mui/icons-material/Refresh';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import WarningIcon from '@mui/icons-material/Warning';
import ErrorIcon from '@mui/icons-material/Error';
import DeleteIcon from '@mui/icons-material/Delete';
import CircularProgress from '@mui/material/CircularProgress';

import { BackendStatus, backendService, InstalledExtension } from '../services/BackendService';
import { FleetExtensionImage } from '../utils/extensionBuilder';
import { ExtensionImageIcon } from './ExtensionImageIcon';
import { useServices } from '../context/ServiceContext';
import { RdctlExtensionsApiResponse } from '../hooks/useBackendInit';

/** Unified image info combining Docker image and extension status */
interface UnifiedImageInfo {
  /** Full image name (repository:tag) */
  imageName: string;
  /** Image ID from Docker */
  id: string;
  /** Repository name */
  repository: string;
  /** Tag */
  tag: string;
  /** Fleet type: base or custom */
  type: 'base' | 'custom';
  /** Human-readable title from OCI label */
  title?: string;
  /** For custom extensions, the base image used */
  baseImage?: string;
  /** Header background color from label */
  headerBackground?: string;
  /** Whether this image is installed as an extension */
  isInstalled: boolean;
  /** Whether this is the currently active (owner) extension */
  isActive: boolean;
  /** Whether this is the extension we're running in */
  isThisExtension: boolean;
  /** Base64 encoded icon data */
  iconData?: string;
  /** MIME type of the icon */
  iconMimeType?: string;
}

export interface EditModeExtensionsTabProps {
  /** Current backend status containing extension and ownership info */
  status: BackendStatus | null;
  /** Whether currently loading */
  loading: boolean;
  /** Callback to refresh status */
  onRefresh: () => void;
  /** Fleet extension images (shared with parent) */
  fleetImages: FleetExtensionImage[];
  /** Whether images are loading */
  loadingImages: boolean;
  /** Callback to refresh fleet images */
  onRefreshImages: () => void;
  /** Our own extension's header background color (from palette) */
  ownHeaderBackground?: string;
  /** Callback to clear all GitRepos when switching extensions */
  onClearAllGitRepos?: () => Promise<void>;
}

/** Operation type for tracking which button is spinning */
type OperationType = 'uninstall' | 'activate' | 'delete';

export function EditModeExtensionsTab({ status, loading, onRefresh, fleetImages, loadingImages, onRefreshImages, ownHeaderBackground, onClearAllGitRepos }: EditModeExtensionsTabProps) {
  const [recheckingOwnership, setRecheckingOwnership] = useState(false);
  const [operatingImage, setOperatingImage] = useState<{ image: string; op: OperationType } | null>(null);
  const [operationError, setOperationError] = useState<string | null>(null);

  const { commandExecutor } = useServices();

  const connected = status?.connected ?? false;
  const initStatus = status?.initStatus;
  const ownership = status?.ownership;
  const kubernetesReady = initStatus?.kubernetesReady ?? false;

  // Use backend's isOwner - each extension runs its own backend with the same image name
  // as the frontend, so the backend correctly identifies itself via Docker lookup
  const isOwner = ownership?.isOwner ?? false;
  const currentOwner = ownership?.currentOwner;

  // Only show ownership status when it's meaningful:
  // - K8s is ready (required for ownership ConfigMap)
  // - Ownership has been determined (not pending/waiting/error)
  const ownershipDetermined = ownership &&
    kubernetesReady &&
    ownership.status !== 'pending' &&
    ownership.status !== 'waiting' &&
    ownership.status !== 'error';

  // Get all installed extensions (for matching with Docker images)
  const allInstalledExtensions = useMemo(
    () => initStatus?.installedExtensions ?? [],
    [initStatus?.installedExtensions]
  );

  // Refresh installed extensions list by re-running rdctl api and updating backend
  const refreshInstalledExtensions = useCallback(async () => {
    try {
      // Run rdctl api /v1/extensions to get current extension list with labels
      const rdctlResult = await commandExecutor.rdExec('rdctl', ['api', '/v1/extensions']);

      if (rdctlResult.stdout) {
        const apiResponse = JSON.parse(rdctlResult.stdout) as RdctlExtensionsApiResponse;
        const installedExtensions: InstalledExtension[] = Object.entries(apiResponse).map(
          ([name, info]) => ({
            name,
            tag: info.version || 'latest',
            labels: info.labels,
          })
        );
        console.log('[ExtensionsTab] Refreshed extensions list:', installedExtensions.map(e => `${e.name}:${e.tag}`));

        // Update backend with new extension list (labels included)
        await backendService.initialize({ installedExtensions });
      }
    } catch (error) {
      console.error('[ExtensionsTab] Failed to refresh extensions list:', error);
    }
  }, [commandExecutor]);

  // Normalize image reference to full form: repository:tag (lowercase)
  const normalizeImageRef = useCallback((name: string): string => {
    const lower = name.toLowerCase();
    return lower.includes(':') ? lower : `${lower}:latest`;
  }, []);

  // Create unified list of all images with their status
  const unifiedImages: UnifiedImageInfo[] = fleetImages.map(img => {
    const imageName = img.repository + (img.tag ? `:${img.tag}` : ':latest');
    const normalizedImageName = normalizeImageRef(imageName);

    // Check if this image is installed as an extension
    // Compare normalized full image names (repository:tag)
    // Note: ext.name is just the repository, ext.tag is the tag
    const installedExt = allInstalledExtensions.find(ext => {
      const extFullName = ext.tag ? `${ext.name}:${ext.tag}` : ext.name;
      const normalizedExtName = normalizeImageRef(extFullName);
      return normalizedExtName === normalizedImageName;
    });

    // Check if this is the extension we're currently running in
    const isThisExtension = !!installedExt && initStatus?.ownIdentity.extensionName === installedExt.name;

    // Check if this is the currently active (owner) extension
    // currentOwner is already defined in outer scope from ownership?.currentOwner
    // If there's only one installed Fleet extension and it's this one, consider it active
    const onlyInstalledExtension = allInstalledExtensions.length === 1 && isThisExtension;
    const isActive = !!installedExt && (
      currentOwner === imageName ||
      currentOwner === normalizedImageName ||
      (isThisExtension && isOwner) ||
      onlyInstalledExtension  // Default to active if only one extension installed
    );

    // Determine header background color:
    // 1. If this is our own extension, use our palette's header background (may have been customized)
    // 2. Otherwise, if the extension has a label, use it
    // 3. Otherwise, use the default icon color (derived from the default Fleet icon)
    const defaultIconColor = '#22ad5f';  // Default Fleet icon green
    const headerBackground = isThisExtension && ownHeaderBackground
      ? ownHeaderBackground
      : (img.headerBackground || defaultIconColor);

    return {
      imageName,
      id: img.id,
      repository: img.repository,
      tag: img.tag,
      type: img.type,
      title: img.title,
      baseImage: img.baseImage,
      headerBackground,
      isInstalled: !!installedExt,
      isActive: !!isActive,
      isThisExtension: !!isThisExtension,
      iconData: img.iconData,
      iconMimeType: img.iconMimeType,
    };
  });

  // Sort so base extension always comes first
  const sortedUnifiedImages = [...unifiedImages].sort((a, b) => {
    if (a.type === 'base' && b.type !== 'base') return -1;
    if (a.type !== 'base' && b.type === 'base') return 1;
    return 0;
  });

  // Find the base image for fallback when deleting/uninstalling active image
  const baseImage = sortedUnifiedImages.find(img => img.type === 'base');

  // Debug logging - log extension matching data to backend
  useEffect(() => {
    if (fleetImages.length > 0 || allInstalledExtensions.length > 0) {
      backendService.debugLog('ExtensionsTab', 'Extension matching data', {
        fleetImages: fleetImages.map(img => ({
          repository: img.repository,
          tag: img.tag,
          type: img.type,
          normalized: normalizeImageRef(img.repository + (img.tag ? `:${img.tag}` : ':latest')),
        })),
        installedExtensions: allInstalledExtensions.map(ext => ({
          name: ext.name,
          tag: ext.tag,
          fullName: ext.tag ? `${ext.name}:${ext.tag}` : ext.name,
          normalized: normalizeImageRef(ext.tag ? `${ext.name}:${ext.tag}` : ext.name),
          hasFleetLabel: ext.hasFleetLabel,
          fleetType: ext.fleetType,
        })),
        unifiedResults: sortedUnifiedImages.map(img => ({
          imageName: img.imageName,
          isInstalled: img.isInstalled,
          isActive: img.isActive,
          isThisExtension: img.isThisExtension,
          type: img.type,
        })),
        ownership: {
          ownExtensionName: ownership?.ownExtensionName,
          currentOwner: ownership?.currentOwner,
          isOwner,
          status: ownership?.status,
        },
        ownIdentity: initStatus?.ownIdentity,
      });
    }
  }, [fleetImages, allInstalledExtensions, sortedUnifiedImages, ownership, isOwner, initStatus, normalizeImageRef]);

  // Uninstall a Fleet extension
  const handleUninstall = async (img: UnifiedImageInfo) => {
    setOperatingImage({ image: img.imageName, op: 'uninstall' });
    setOperationError(null);

    try {
      const result = await commandExecutor.rdExec('rdctl', [
        'extension',
        'uninstall',
        img.imageName,
      ]);

      if (result.stderr && result.stderr.includes('Error')) {
        throw new Error(result.stderr);
      }

      // If this was the active extension and there's a base image, activate the base
      if (img.isActive && baseImage && baseImage.imageName !== img.imageName) {
        console.log(`[ExtensionsTab] Activating base extension after uninstall: ${baseImage.imageName}`);

        // Ensure base is installed
        if (!baseImage.isInstalled) {
          const installResult = await commandExecutor.rdExec('rdctl', [
            'extension',
            'install',
            baseImage.imageName,
          ]);
          if (installResult.stderr && installResult.stderr.includes('Error')) {
            console.warn('Failed to install base extension:', installResult.stderr);
          }
        }

        // Transfer ownership to base
        await backendService.transferOwnership(baseImage.imageName);
      }

      // Refresh extension list and UI after successful uninstall
      await onRefreshImages();
      await refreshInstalledExtensions();
      onRefresh();
    } catch (error) {
      console.error('Failed to uninstall extension:', error);
      setOperationError(error instanceof Error ? error.message : 'Failed to uninstall extension');
    } finally {
      setOperatingImage(null);
    }
  };

  // Activate an extension (transfer ownership to it)
  const handleActivate = async (img: UnifiedImageInfo) => {
    setOperatingImage({ image: img.imageName, op: 'activate' });
    setOperationError(null);

    try {
      // If not installed, install it first (inline to avoid operatingImage being cleared by handleInstall)
      if (!img.isInstalled) {
        console.log(`[ExtensionsTab] Installing ${img.imageName} before activation...`);
        const result = await commandExecutor.rdExec('rdctl', [
          'extension',
          'install',
          img.imageName,
        ]);

        if (result.stderr && result.stderr.includes('Error')) {
          throw new Error(result.stderr);
        }

        // Refresh extension list after install
        await refreshInstalledExtensions();
      }

      // Clear all GitRepos before switching - the new extension will initialize from its manifest
      if (onClearAllGitRepos) {
        console.log('[ExtensionsTab] Clearing all GitRepos before switching extensions...');
        await onClearAllGitRepos();
      }

      // Transfer ownership using the full image name as the canonical identifier
      console.log(`[ExtensionsTab] Transferring ownership to: ${img.imageName}`);
      await backendService.transferOwnership(img.imageName);

      // Refresh to show updated status
      await onRefreshImages();
      onRefresh();
    } catch (error) {
      console.error('Failed to activate extension:', error);
      setOperationError(error instanceof Error ? error.message : 'Failed to activate extension');
    } finally {
      setOperatingImage(null);
    }
  };

  // Delete a Docker image
  const handleDelete = async (img: UnifiedImageInfo) => {
    setOperatingImage({ image: img.imageName, op: 'delete' });
    setOperationError(null);

    try {
      // If installed, uninstall first
      if (img.isInstalled) {
        const uninstallResult = await commandExecutor.rdExec('rdctl', [
          'extension',
          'uninstall',
          img.imageName,
        ]);

        if (uninstallResult.stderr && uninstallResult.stderr.includes('Error')) {
          throw new Error(uninstallResult.stderr);
        }

        // If this was the active image and there's a base image, activate the base
        if (img.isActive && baseImage && baseImage.imageName !== img.imageName) {
          console.log(`[ExtensionsTab] Activating base extension after delete: ${baseImage.imageName}`);

          // Ensure base is installed
          if (!baseImage.isInstalled) {
            const installResult = await commandExecutor.rdExec('rdctl', [
              'extension',
              'install',
              baseImage.imageName,
            ]);
            if (installResult.stderr && installResult.stderr.includes('Error')) {
              console.warn('Failed to install base extension:', installResult.stderr);
            }
          }

          // Transfer ownership to base
          await backendService.transferOwnership(baseImage.imageName);
        }
      }

      // Delete the Docker image
      const deleteResult = await commandExecutor.rdExec('docker', [
        'rmi',
        img.imageName,
      ]);

      if (deleteResult.stderr && deleteResult.stderr.includes('Error')) {
        throw new Error(deleteResult.stderr);
      }

      // Refresh extension list and UI after successful delete
      await onRefreshImages();
      await refreshInstalledExtensions();
      onRefresh();
    } catch (error) {
      console.error('Failed to delete image:', error);
      setOperationError(error instanceof Error ? error.message : 'Failed to delete image');
    } finally {
      setOperatingImage(null);
    }
  };

  const handleRefresh = async () => {
    setRecheckingOwnership(true);
    try {
      await backendService.recheckOwnership();
    } catch (error) {
      console.error('Failed to recheck ownership:', error);
    } finally {
      setRecheckingOwnership(false);
    }
    onRefresh();
    onRefreshImages();
  };

  return (
    <Box>
      {/* Header with status and refresh */}
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 2 }}>
        <Typography variant="subtitle2" sx={{ fontWeight: 600, flexGrow: 1 }}>
          Fleet Extensions Status
        </Typography>

        {/* Extension count chip */}
        <Chip
          size="small"
          label={`${sortedUnifiedImages.filter(i => i.isInstalled).length} installed, ${sortedUnifiedImages.length} images`}
          color="primary"
          variant="outlined"
        />

        {/* Show initializing chip when K8s not ready or ownership pending */}
        {connected && !ownershipDetermined && (
          <Chip
            size="small"
            label={!kubernetesReady ? 'K8s not ready' : 'Initializing...'}
            color="default"
            variant="outlined"
          />
        )}

        <Tooltip title="Refresh status and images">
          <IconButton size="small" onClick={handleRefresh} disabled={loading || loadingImages || recheckingOwnership}>
            {(loading || recheckingOwnership) ? <CircularProgress size={16} /> : <RefreshIcon fontSize="small" />}
          </IconButton>
        </Tooltip>
      </Box>

      {/* Connection status message */}
      {!connected && (
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 2, color: 'text.secondary' }}>
          <ErrorIcon fontSize="small" color="error" />
          <Typography variant="body2">
            Backend service not connected. Extension ownership cannot be determined.
          </Typography>
        </Box>
      )}

      {/* K8s not ready message */}
      {connected && !kubernetesReady && (
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 2, color: 'text.secondary' }}>
          <CircularProgress size={16} />
          <Typography variant="body2">
            Waiting for Kubernetes to be ready...
          </Typography>
        </Box>
      )}

      {/* Ownership explanation - only show when determined */}
      {ownershipDetermined && (
        <Box
          sx={{
            mb: 2,
            p: 1.5,
            borderRadius: 1,
            bgcolor: isOwner ? 'success.light' : 'warning.light',
            display: 'flex',
            alignItems: 'center',
            gap: 1,
          }}
        >
          {isOwner ? (
            <CheckCircleIcon color="success" />
          ) : (
            <WarningIcon color="warning" />
          )}
          <Typography variant="body2" sx={{ fontWeight: 600 }}>
            {isOwner
              ? 'This extension controls Fleet'
              : `Another extension controls Fleet: ${ownership.currentOwner}`
            }
          </Typography>
        </Box>
      )}

      {/* Fleet Extension Images List */}
      {sortedUnifiedImages.length > 0 ? (
        <Box>
          {operationError && (
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1, color: 'error.main' }}>
              <ErrorIcon fontSize="small" />
              <Typography variant="caption">{operationError}</Typography>
            </Box>
          )}
          <List dense disablePadding>
            {sortedUnifiedImages.map((img, index) => {
              // Check if this specific image+operation is in progress
              const isActivating = operatingImage?.image === img.imageName && operatingImage?.op === 'activate';
              const isUninstalling = operatingImage?.image === img.imageName && operatingImage?.op === 'uninstall';
              const isDeleting = operatingImage?.image === img.imageName && operatingImage?.op === 'delete';
              const canModify = img.type !== 'base'; // Base image cannot be uninstalled or deleted

              return (
                <ListItem
                  key={index}
                  sx={() => {
                    const baseStyles = {
                      borderRadius: 1,
                      mb: 0.5,
                      pr: 1,
                    };

                    // Use the extension's header background color (always set, with default)
                    const headerColor = img.headerBackground || '#22ad5f';

                    // For inactive extensions, show diagonal stripes to indicate
                    // the extension is not currently controlling fleet
                    if (!img.isActive) {
                      const darkStripe = alpha(headerColor, 0.35);
                      const lightStripe = alpha(headerColor, 0.15);

                      return {
                        ...baseStyles,
                        background: `repeating-linear-gradient(
                          -45deg,
                          ${darkStripe},
                          ${darkStripe} 6px,
                          ${lightStripe} 6px,
                          ${lightStripe} 12px
                        )`,
                      };
                    }

                    // Active extension gets solid background using its header color
                    return {
                      ...baseStyles,
                      bgcolor: alpha(headerColor, 0.2),
                    };
                  }}
                  secondaryAction={
                    <Box sx={{ display: 'flex', gap: 0.5, alignItems: 'center' }}>
                      {/* Uninstall button - show if installed and not base image */}
                      {img.isInstalled && canModify && (
                        <Button
                          size="small"
                          variant="outlined"
                          color="warning"
                          onClick={() => handleUninstall(img)}
                          disabled={!!operatingImage}
                          startIcon={isUninstalling ? <CircularProgress size={14} /> : undefined}
                          sx={{ minWidth: 'auto', px: 1, py: 0.25, fontSize: '0.75rem' }}
                        >
                          {isUninstalling ? 'Uninstalling...' : 'Uninstall'}
                        </Button>
                      )}
                      {/* Delete button - show if not base image */}
                      {canModify && (
                        <Tooltip
                          title={img.isInstalled ? 'Uninstall and delete image' : 'Delete image'}
                          placement="top"
                          enterDelay={500}
                          enterNextDelay={500}
                        >
                          <IconButton
                            size="small"
                            color="error"
                            onClick={() => handleDelete(img)}
                            disabled={!!operatingImage}
                          >
                            {isDeleting ? <CircularProgress size={18} /> : <DeleteIcon fontSize="small" />}
                          </IconButton>
                        </Tooltip>
                      )}
                    </Box>
                  }
                >
                  {/* Radio button for selecting active extension */}
                  <ListItemIcon sx={{ minWidth: 32 }}>
                    {isActivating ? (
                      <CircularProgress size={20} sx={{ ml: 0.25 }} />
                    ) : (
                      <Tooltip
                        title={img.isActive ? 'Active extension' : 'Click to activate'}
                        placement="top"
                        enterDelay={500}
                        enterNextDelay={500}
                      >
                        <span>
                          <Radio
                            size="small"
                            checked={img.isActive}
                            onChange={() => !img.isActive && handleActivate(img)}
                            disabled={!!operatingImage || !ownershipDetermined}
                            sx={{ p: 0.5 }}
                          />
                        </span>
                      </Tooltip>
                    )}
                  </ListItemIcon>
                  {/* Extension icon */}
                  <ListItemIcon sx={{ minWidth: 28 }}>
                    <ExtensionImageIcon
                      iconData={img.iconData}
                      iconMimeType={img.iconMimeType}
                      size={20}
                      fallbackColor={img.isInstalled ? 'primary' : 'action'}
                    />
                  </ListItemIcon>
                  <ListItemText
                    primary={
                      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                        <Typography variant="body2" sx={{ fontFamily: 'monospace' }}>
                          {img.imageName}
                        </Typography>
                        {img.isThisExtension && (
                          <Chip
                            size="small"
                            label="This"
                            color="primary"
                            variant="outlined"
                            sx={{ height: 18, fontSize: '0.65rem' }}
                          />
                        )}
                        {img.type && (
                          <Chip
                            size="small"
                            label={img.type}
                            color={img.type === 'base' ? 'info' : 'default'}
                            variant="outlined"
                            sx={{ height: 18, fontSize: '0.65rem' }}
                          />
                        )}
                        {!img.isInstalled && (
                          <Chip
                            size="small"
                            label="not installed"
                            color="default"
                            variant="outlined"
                            sx={{ height: 18, fontSize: '0.65rem' }}
                          />
                        )}
                      </Box>
                    }
                  />
                </ListItem>
              );
            })}
          </List>
        </Box>
      ) : connected ? (
        <Typography variant="body2" color="text.secondary">
          No Fleet extension images found.
        </Typography>
      ) : null}


    </Box>
  );
}

export default EditModeExtensionsTab;

// extension/ui-vue/src/components/EditModeExtensionsTab.vue
<script setup lang="ts">
/**
 * EditModeExtensionsTab - Tab content for Fleet extensions management in edit mode.
 *
 * Shows:
 * - List of installed Fleet extensions with their status
 * - List of Fleet extension images (built but not installed)
 * - Which extension currently owns/controls Fleet
 * - Actions to take control if applicable
 */

import { ref, computed, onMounted } from 'vue';
import { backendService, type BackendStatus, type FleetImageWithIcon } from '../services/BackendService';
import { ddClient } from '../lib/ddClient';

// Props
const props = defineProps<{
  ownHeaderBackground?: string;
}>();

// Emits
const emit = defineEmits<{
  clearAllGitRepos: [];
}>();

// State
const loading = ref(false);
const loadingImages = ref(false);
const recheckingOwnership = ref(false);
const status = ref<BackendStatus | null>(null);
const fleetImages = ref<FleetImageWithIcon[]>([]);
const operatingImage = ref<{ image: string; op: 'uninstall' | 'activate' | 'delete' } | null>(null);
const operationError = ref<string | null>(null);

// Computed values
const connected = computed(() => status.value?.connected ?? false);
const initStatus = computed(() => status.value?.initStatus);
const ownership = computed(() => status.value?.ownership);
const kubernetesReady = computed(() => initStatus.value?.kubernetesReady ?? false);
const isOwner = computed(() => ownership.value?.isOwner ?? false);
const currentOwner = computed(() => ownership.value?.currentOwner);

const ownershipDetermined = computed(() => {
  return ownership.value &&
    kubernetesReady.value &&
    ownership.value.status !== 'pending' &&
    ownership.value.status !== 'waiting' &&
    ownership.value.status !== 'error';
});

const allInstalledExtensions = computed(() => initStatus.value?.installedExtensions ?? []);

// Normalize image reference to full form: repository:tag (lowercase)
function normalizeImageRef(name: string): string {
  const lower = name.toLowerCase();
  return lower.includes(':') ? lower : `${lower}:latest`;
}

// Unified image info interface
interface UnifiedImageInfo {
  imageName: string;
  id: string;
  repository: string;
  tag: string;
  type: 'base' | 'custom';
  title?: string;
  baseImage?: string;
  headerBackground?: string;
  isInstalled: boolean;
  isActive: boolean;
  isThisExtension: boolean;
  iconData?: string;
  iconMimeType?: string;
}

// Create unified list of images with status
const unifiedImages = computed<UnifiedImageInfo[]>(() => {
  return fleetImages.value.map(img => {
    const imageName = img.repository + (img.tag ? `:${img.tag}` : ':latest');
    const normalizedImageName = normalizeImageRef(imageName);

    // Check if installed
    const installedExt = allInstalledExtensions.value.find(ext => {
      const extFullName = ext.tag ? `${ext.name}:${ext.tag}` : ext.name;
      const normalizedExtName = normalizeImageRef(extFullName);
      return normalizedExtName === normalizedImageName;
    });

    // Check if this is the extension we're running in
    const isThisExtension = !!installedExt && initStatus.value?.ownIdentity.extensionName === installedExt.name;

    // Check if active
    const onlyInstalledExtension = allInstalledExtensions.value.length === 1 && isThisExtension;
    const isActive = !!installedExt && (
      currentOwner.value === imageName ||
      currentOwner.value === normalizedImageName ||
      (isThisExtension && isOwner.value) ||
      onlyInstalledExtension
    );

    // Determine header background color
    const defaultIconColor = '#22ad5f';
    const headerBackground = isThisExtension && props.ownHeaderBackground
      ? props.ownHeaderBackground
      : (img.headerBackground || defaultIconColor);

    return {
      imageName,
      id: img.id,
      repository: img.repository,
      tag: img.tag,
      type: img.type,
      title: img.title,
      baseImage: img.baseImage,
      headerBackground,
      isInstalled: !!installedExt,
      isActive: !!isActive,
      isThisExtension: !!isThisExtension,
      iconData: img.iconData,
      iconMimeType: img.iconMimeType,
    };
  });
});

// Sort so base extension always comes first
const sortedUnifiedImages = computed(() => {
  return [...unifiedImages.value].sort((a, b) => {
    if (a.type === 'base' && b.type !== 'base') return -1;
    if (a.type !== 'base' && b.type === 'base') return 1;
    return 0;
  });
});

// Find base image for fallback
const baseImage = computed(() => sortedUnifiedImages.value.find(img => img.type === 'base'));

// Extension count text
const extensionCountText = computed(() => {
  const installed = sortedUnifiedImages.value.filter(i => i.isInstalled).length;
  const total = sortedUnifiedImages.value.length;
  return `${installed} installed, ${total} images`;
});

// Execute rdctl command
async function rdExec(command: string, args: string[]): Promise<{ stdout: string; stderr: string }> {
  const result = await ddClient.extension.host?.cli.exec(command, args);
  return {
    stdout: result?.stdout ?? '',
    stderr: result?.stderr ?? '',
  };
}

// Fetch backend status
async function fetchStatus() {
  loading.value = true;
  try {
    status.value = await backendService.getStatus();
  } catch (error) {
    console.error('Failed to fetch status:', error);
    status.value = {
      connected: false,
      error: error instanceof Error ? error.message : 'Unknown error',
      lastChecked: new Date().toISOString(),
    };
  } finally {
    loading.value = false;
  }
}

// Fetch fleet images
async function fetchImages() {
  loadingImages.value = true;
  try {
    const response = await backendService.getFleetIcons();
    fleetImages.value = response.images;
  } catch (error) {
    console.error('Failed to fetch images:', error);
    fleetImages.value = [];
  } finally {
    loadingImages.value = false;
  }
}

// Refresh installed extensions list
async function refreshInstalledExtensions() {
  try {
    const result = await rdExec('rdctl', ['api', '/v1/extensions']);
    if (result.stdout) {
      const apiResponse = JSON.parse(result.stdout) as Record<string, { version?: string; labels?: Record<string, string> }>;
      const installedExtensions = Object.entries(apiResponse).map(([name, info]) => ({
        name,
        tag: info.version || 'latest',
        labels: info.labels,
      }));
      await backendService.initialize({ installedExtensions });
    }
  } catch (error) {
    console.error('Failed to refresh extensions list:', error);
  }
}

// Handle uninstall
async function handleUninstall(img: UnifiedImageInfo) {
  operatingImage.value = { image: img.imageName, op: 'uninstall' };
  operationError.value = null;

  try {
    const result = await rdExec('rdctl', ['extension', 'uninstall', img.imageName]);

    if (result.stderr?.includes('Error')) {
      throw new Error(result.stderr);
    }

    // If this was active and there's a base image, activate base
    if (img.isActive && baseImage.value && baseImage.value.imageName !== img.imageName) {
      if (!baseImage.value.isInstalled) {
        await rdExec('rdctl', ['extension', 'install', baseImage.value.imageName]);
      }
      // Transfer ownership to base would require backend API
    }

    await fetchImages();
    await refreshInstalledExtensions();
    await fetchStatus();
  } catch (error) {
    console.error('Failed to uninstall extension:', error);
    operationError.value = error instanceof Error ? error.message : 'Failed to uninstall extension';
  } finally {
    operatingImage.value = null;
  }
}

// Handle activate
async function handleActivate(img: UnifiedImageInfo) {
  operatingImage.value = { image: img.imageName, op: 'activate' };
  operationError.value = null;

  try {
    // Install if not installed
    if (!img.isInstalled) {
      const result = await rdExec('rdctl', ['extension', 'install', img.imageName]);
      if (result.stderr?.includes('Error')) {
        throw new Error(result.stderr);
      }
      await refreshInstalledExtensions();
    }

    // Clear GitRepos before switching
    emit('clearAllGitRepos');

    // Transfer ownership (would need backend API)
    console.log(`Activating extension: ${img.imageName}`);

    await fetchImages();
    await fetchStatus();
  } catch (error) {
    console.error('Failed to activate extension:', error);
    operationError.value = error instanceof Error ? error.message : 'Failed to activate extension';
  } finally {
    operatingImage.value = null;
  }
}

// Handle delete
async function handleDelete(img: UnifiedImageInfo) {
  operatingImage.value = { image: img.imageName, op: 'delete' };
  operationError.value = null;

  try {
    // Uninstall first if installed
    if (img.isInstalled) {
      const uninstallResult = await rdExec('rdctl', ['extension', 'uninstall', img.imageName]);
      if (uninstallResult.stderr?.includes('Error')) {
        throw new Error(uninstallResult.stderr);
      }

      // Activate base if this was active
      if (img.isActive && baseImage.value && baseImage.value.imageName !== img.imageName) {
        if (!baseImage.value.isInstalled) {
          await rdExec('rdctl', ['extension', 'install', baseImage.value.imageName]);
        }
      }
    }

    // Delete Docker image
    const deleteResult = await rdExec('docker', ['rmi', img.imageName]);
    if (deleteResult.stderr?.includes('Error')) {
      throw new Error(deleteResult.stderr);
    }

    await fetchImages();
    await refreshInstalledExtensions();
    await fetchStatus();
  } catch (error) {
    console.error('Failed to delete image:', error);
    operationError.value = error instanceof Error ? error.message : 'Failed to delete image';
  } finally {
    operatingImage.value = null;
  }
}

// Handle refresh
async function handleRefresh() {
  recheckingOwnership.value = true;
  try {
    await fetchStatus();
    await fetchImages();
  } finally {
    recheckingOwnership.value = false;
  }
}

// Get list item background style
function getListItemStyle(img: UnifiedImageInfo): Record<string, string> {
  const headerColor = img.headerBackground || '#22ad5f';

  if (!img.isActive) {
    // Diagonal stripes for inactive
    return {
      background: `repeating-linear-gradient(
        -45deg,
        ${hexToRgba(headerColor, 0.35)},
        ${hexToRgba(headerColor, 0.35)} 6px,
        ${hexToRgba(headerColor, 0.15)} 6px,
        ${hexToRgba(headerColor, 0.15)} 12px
      )`,
      borderRadius: '4px',
      marginBottom: '4px',
    };
  }

  // Solid background for active
  return {
    backgroundColor: hexToRgba(headerColor, 0.2),
    borderRadius: '4px',
    marginBottom: '4px',
  };
}

// Convert hex to rgba
function hexToRgba(hex: string, alpha: number): string {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

// Initialize on mount
onMounted(async () => {
  await fetchStatus();
  await fetchImages();
});
</script>

<template>
  <div class="extensions-tab">
    <!-- Header with status and refresh -->
    <div class="d-flex align-center mb-4">
      <span class="text-subtitle-2 font-weight-bold flex-grow-1">
        Fleet Extensions Status
      </span>

      <!-- Extension count chip -->
      <v-chip size="small" color="primary" variant="outlined" class="mr-2">
        {{ extensionCountText }}
      </v-chip>

      <!-- Initializing chip -->
      <v-chip
        v-if="connected && !ownershipDetermined"
        size="small"
        color="default"
        variant="outlined"
        class="mr-2"
      >
        {{ !kubernetesReady ? 'K8s not ready' : 'Initializing...' }}
      </v-chip>

      <!-- Refresh button -->
      <v-btn
        icon
        size="small"
        :loading="loading || loadingImages || recheckingOwnership"
        @click="handleRefresh"
      >
        <v-icon icon="mdi-refresh" />
      </v-btn>
    </div>

    <!-- Connection error message -->
    <v-alert
      v-if="!connected"
      type="error"
      variant="tonal"
      density="compact"
      class="mb-4"
    >
      <div class="d-flex align-center">
        <v-icon icon="mdi-alert-circle" class="mr-2" />
        Backend service not connected. Extension ownership cannot be determined.
      </div>
    </v-alert>

    <!-- K8s not ready message -->
    <v-alert
      v-else-if="!kubernetesReady"
      type="info"
      variant="tonal"
      density="compact"
      class="mb-4"
    >
      <div class="d-flex align-center">
        <v-progress-circular indeterminate size="16" width="2" class="mr-2" />
        Waiting for Kubernetes to be ready...
      </div>
    </v-alert>

    <!-- Ownership status -->
    <v-alert
      v-if="ownershipDetermined"
      :type="isOwner ? 'success' : 'warning'"
      variant="tonal"
      density="compact"
      class="mb-4"
    >
      <div class="d-flex align-center">
        <v-icon :icon="isOwner ? 'mdi-check-circle' : 'mdi-alert'" class="mr-2" />
        <span class="font-weight-bold">
          {{ isOwner
            ? 'This extension controls Fleet'
            : `Another extension controls Fleet: ${ownership?.currentOwner}`
          }}
        </span>
      </div>
    </v-alert>

    <!-- Operation error -->
    <v-alert
      v-if="operationError"
      type="error"
      variant="tonal"
      density="compact"
      class="mb-4"
      closable
      @click:close="operationError = null"
    >
      {{ operationError }}
    </v-alert>

    <!-- Extensions list -->
    <v-list v-if="sortedUnifiedImages.length > 0" density="compact" class="pa-0">
      <v-list-item
        v-for="img in sortedUnifiedImages"
        :key="img.id"
        :style="getListItemStyle(img)"
        class="pr-1"
      >
        <!-- Prepend: Radio button + Extension icon -->
        <template #prepend>
          <div class="d-flex align-center">
            <v-progress-circular
              v-if="operatingImage?.image === img.imageName && operatingImage?.op === 'activate'"
              indeterminate
              size="20"
              width="2"
              class="mr-2"
            />
            <v-radio-group
              v-else
              :model-value="img.isActive ? img.imageName : null"
              hide-details
              class="ma-0 pa-0 mr-1"
            >
              <v-radio
                :value="img.imageName"
                :disabled="!!operatingImage || !ownershipDetermined"
                density="compact"
                @click="!img.isActive && handleActivate(img)"
              />
            </v-radio-group>

            <v-icon
              v-if="!img.iconData"
              icon="mdi-puzzle"
              :color="img.isInstalled ? 'primary' : 'grey'"
              size="20"
              class="mr-2"
            />
            <v-avatar v-else size="20" class="mr-2">
              <v-img :src="`data:${img.iconMimeType};base64,${img.iconData}`" />
            </v-avatar>
          </div>
        </template>

        <!-- Content -->
        <v-list-item-title class="d-flex align-center flex-wrap">
          <code class="text-body-2 mr-2">{{ img.imageName }}</code>
          <v-chip
            v-if="img.isThisExtension"
            size="x-small"
            color="primary"
            variant="outlined"
            class="mr-1"
          >
            This
          </v-chip>
          <v-chip
            v-if="img.type"
            size="x-small"
            :color="img.type === 'base' ? 'info' : 'default'"
            variant="outlined"
            class="mr-1"
          >
            {{ img.type }}
          </v-chip>
          <v-chip
            v-if="!img.isInstalled"
            size="x-small"
            color="default"
            variant="outlined"
          >
            not installed
          </v-chip>
        </v-list-item-title>

        <!-- Actions -->
        <template #append>
          <div class="d-flex align-center">
            <!-- Uninstall button -->
            <v-btn
              v-if="img.isInstalled && img.type !== 'base'"
              size="x-small"
              variant="outlined"
              color="warning"
              :loading="operatingImage?.image === img.imageName && operatingImage?.op === 'uninstall'"
              :disabled="!!operatingImage"
              class="mr-1"
              @click="handleUninstall(img)"
            >
              Uninstall
            </v-btn>

            <!-- Delete button -->
            <v-btn
              v-if="img.type !== 'base'"
              icon
              size="x-small"
              color="error"
              variant="text"
              :loading="operatingImage?.image === img.imageName && operatingImage?.op === 'delete'"
              :disabled="!!operatingImage"
              :title="img.isInstalled ? 'Uninstall and delete image' : 'Delete image'"
              @click="handleDelete(img)"
            >
              <v-icon icon="mdi-delete" size="18" />
            </v-btn>
          </div>
        </template>
      </v-list-item>
    </v-list>

    <!-- Empty state -->
    <div v-else-if="connected && !loadingImages" class="text-body-2 text-grey">
      No Fleet extension images found.
    </div>

    <!-- Loading state -->
    <div v-else-if="loadingImages" class="d-flex align-center justify-center py-4">
      <v-progress-circular indeterminate size="24" />
      <span class="ml-2 text-grey">Loading extensions...</span>
    </div>
  </div>
</template>

<style scoped>
.extensions-tab code {
  font-family: monospace;
  font-size: 0.875rem;
}
</style>
