// extension/ui/src/cards/VideoCard.tsx
import React from 'react';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import TextField from '@mui/material/TextField';
import { CardProps } from './types';
import { VideoCardSettings } from '../manifest/types';
import { registerCard } from './registry';

// Convert YouTube/Vimeo URLs to embed URLs
function getEmbedUrl(url: string): { type: 'embed' | 'video'; url: string } {
  // YouTube URLs
  const youtubeMatch = url.match(
    /(?:youtube\.com\/(?:watch\?v=|embed\/)|youtu\.be\/)([a-zA-Z0-9_-]{11})/
  );
  if (youtubeMatch) {
    return { type: 'embed', url: `https://www.youtube.com/embed/${youtubeMatch[1]}` };
  }

  // Vimeo URLs
  const vimeoMatch = url.match(/(?:vimeo\.com\/|player\.vimeo\.com\/video\/)(\d+)/);
  if (vimeoMatch) {
    return { type: 'embed', url: `https://player.vimeo.com/video/${vimeoMatch[1]}` };
  }

  // Direct video URL
  return { type: 'video', url };
}

export const VideoCard: React.FC<CardProps<VideoCardSettings>> = ({
  definition,
  settings,
  editMode = false,
  onSettingsChange,
}) => {
  const src = settings?.src || '';
  const title = settings?.title || '';

  if (editMode && onSettingsChange) {
    return (
      <Box>
        {definition.title && (
          <Typography variant="h6" gutterBottom>
            {definition.title}
          </Typography>
        )}
        <TextField
          fullWidth
          label="Video URL"
          value={src}
          onChange={(e) => onSettingsChange({ ...settings, src: e.target.value })}
          placeholder="https://youtube.com/watch?v=... or direct video URL"
          variant="outlined"
          size="small"
          helperText="Supports YouTube, Vimeo, or direct video URLs (.mp4, .webm)"
          sx={{ mb: 2 }}
        />
        <TextField
          fullWidth
          label="Title (optional)"
          value={title}
          onChange={(e) => onSettingsChange({ ...settings, title: e.target.value })}
          placeholder="Video title for accessibility"
          variant="outlined"
          size="small"
          sx={{ mb: 2 }}
        />
        {src && (
          <Box sx={{ mt: 1, p: 1, border: '1px solid', borderColor: 'divider', borderRadius: 1 }}>
            <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 1 }}>
              Preview:
            </Typography>
            <VideoPlayer src={src} title={title} />
          </Box>
        )}
      </Box>
    );
  }

  if (!src) {
    return (
      <Box sx={{ p: 2, textAlign: 'center', color: 'text.secondary' }}>
        <Typography variant="body2">No video configured</Typography>
      </Box>
    );
  }

  return (
    <Box>
      {definition.title && (
        <Typography variant="h6" gutterBottom>
          {definition.title}
        </Typography>
      )}
      <VideoPlayer src={src} title={title} />
    </Box>
  );
};

// Separate component for rendering video to avoid duplication
const VideoPlayer: React.FC<{ src: string; title: string }> = ({ src, title }) => {
  const { type, url } = getEmbedUrl(src);

  if (type === 'embed') {
    return (
      <Box
        sx={{
          position: 'relative',
          paddingBottom: '56.25%', // 16:9 aspect ratio
          height: 0,
          overflow: 'hidden',
          borderRadius: 1,
        }}
      >
        <Box
          component="iframe"
          src={url}
          title={title || 'Embedded video'}
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowFullScreen
          sx={{
            position: 'absolute',
            top: 0,
            left: 0,
            width: '100%',
            height: '100%',
            border: 'none',
            borderRadius: 1,
          }}
        />
      </Box>
    );
  }

  return (
    <Box
      component="video"
      controls
      src={url}
      title={title}
      sx={{
        maxWidth: '100%',
        maxHeight: 400,
        borderRadius: 1,
        display: 'block',
      }}
    >
      Your browser does not support the video tag.
    </Box>
  );
};

// Register the video card
registerCard('video', VideoCard);

export default VideoCard;

// extension/ui-vue/src/components/cards/VideoCard.vue
<script setup lang="ts">
/**
 * VideoCard - Embeds video content (YouTube, etc.).
 */
import { computed } from 'vue';
import CardWrapper from './CardWrapper.vue';
import type { VideoCardSettings } from '../../types/manifest';

const props = defineProps<{
  title?: string;
  settings?: VideoCardSettings;
}>();

// Convert YouTube URLs to embed format
const embedUrl = computed(() => {
  const src = props.settings?.src ?? '';

  // Handle YouTube URLs
  const youtubeMatch = src.match(
    /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([^&?/]+)/
  );
  if (youtubeMatch) {
    return `https://www.youtube.com/embed/${youtubeMatch[1]}`;
  }

  return src;
});

const videoTitle = computed(() => props.settings?.title ?? props.title ?? 'Video');
</script>

<template>
  <CardWrapper :title="title" no-padding>
    <div v-if="embedUrl" class="video-container">
      <iframe
        :src="embedUrl"
        :title="videoTitle"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen
      />
    </div>
    <div v-else class="no-video">
      <v-icon icon="mdi-video-off" size="48" color="grey" />
      <p class="text-grey">No video configured</p>
    </div>
  </CardWrapper>
</template>

<style scoped>
.video-container {
  position: relative;
  padding-bottom: 56.25%; /* 16:9 aspect ratio */
  height: 0;
  overflow: hidden;
}

.video-container iframe {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}

.no-video {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 32px;
}
</style>
