// extension/ui/src/components/DependencyConfirmationDialog.tsx
/**
 * DependencyConfirmationDialog component - Confirms enabling paths with dependencies.
 *
 * This is a pure presentational component that receives all data via props,
 * making it easily testable without complex mocking.
 */

import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import Chip from '@mui/material/Chip';
import Dialog from '@mui/material/Dialog';
import DialogTitle from '@mui/material/DialogTitle';
import DialogContent from '@mui/material/DialogContent';
import DialogContentText from '@mui/material/DialogContentText';
import DialogActions from '@mui/material/DialogActions';

import { BundleInfo } from '../types';

/** State for the dependency dialog */
export interface DependencyDialogState {
  open: boolean;
  gitRepoName: string;
  path: string;
  willAutoSelect: BundleInfo[];
}

/** Initial/closed state for the dialog */
export const INITIAL_DEPENDENCY_DIALOG_STATE: DependencyDialogState = {
  open: false,
  gitRepoName: '',
  path: '',
  willAutoSelect: [],
};

/** Props for the DependencyConfirmationDialog component */
export interface DependencyConfirmationDialogProps {
  /** Current dialog state */
  state: DependencyDialogState;
  /** Callback when dialog is closed/cancelled */
  onClose: () => void;
  /** Callback when user confirms enabling dependencies */
  onConfirm: () => void;
}

/**
 * DependencyConfirmationDialog - Shows dependencies that will be enabled.
 *
 * When a user tries to enable a path that has dependencies, this dialog
 * shows them what other paths will also be enabled and asks for confirmation.
 */
export function DependencyConfirmationDialog({
  state,
  onClose,
  onConfirm,
}: DependencyConfirmationDialogProps) {
  return (
    <Dialog
      open={state.open}
      onClose={onClose}
      maxWidth="sm"
      fullWidth
    >
      <DialogTitle>Enable Dependencies</DialogTitle>
      <DialogContent>
        <DialogContentText sx={{ mb: 2 }}>
          The path <strong>{state.path}</strong> has dependencies that will also be enabled:
        </DialogContentText>
        <Box sx={{ pl: 2 }}>
          {state.willAutoSelect.map((dep) => (
            <Box key={dep.bundleName} sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 0.5 }}>
              <Typography variant="body2" sx={{ fontFamily: 'monospace' }}>
                {dep.path}
              </Typography>
              {dep.gitRepoName !== state.gitRepoName && (
                <Chip
                  size="small"
                  label={dep.gitRepoName}
                  variant="outlined"
                  sx={{ height: 18, fontSize: '0.7rem' }}
                />
              )}
            </Box>
          ))}
        </Box>
      </DialogContent>
      <DialogActions>
        <Button onClick={onClose}>
          Cancel
        </Button>
        <Button variant="contained" onClick={onConfirm}>
          Enable All
        </Button>
      </DialogActions>
    </Dialog>
  );
}

export default DependencyConfirmationDialog;

// extension/ui-vue/src/components/dialogs/DependencyConfirmationDialog.vue
<script setup lang="ts">
/**
 * DependencyConfirmationDialog - Confirms enabling paths with dependencies.
 *
 * When a user tries to enable a path that has dependencies, this dialog
 * shows them what other paths will also be enabled and asks for confirmation.
 */

interface BundleInfo {
  bundleName: string;
  path: string;
  gitRepoName: string;
}

export interface DependencyDialogState {
  open: boolean;
  gitRepoName: string;
  path: string;
  willAutoSelect: BundleInfo[];
}

defineProps<{
  state: DependencyDialogState;
}>();

const emit = defineEmits<{
  (e: 'close'): void;
  (e: 'confirm'): void;
}>();
</script>

<template>
  <v-dialog
    :model-value="state.open"
    max-width="500"
    @update:model-value="!$event && emit('close')"
  >
    <v-card>
      <v-card-title>Enable Dependencies</v-card-title>
      <v-card-text>
        <p class="text-body-1 mb-4">
          The path <strong>{{ state.path }}</strong> has dependencies that will also be enabled:
        </p>
        <div class="pl-4">
          <div
            v-for="dep in state.willAutoSelect"
            :key="dep.bundleName"
            class="d-flex align-center ga-2 mb-1"
          >
            <span class="text-body-2 font-mono">{{ dep.path }}</span>
            <v-chip
              v-if="dep.gitRepoName !== state.gitRepoName"
              size="x-small"
              variant="outlined"
            >
              {{ dep.gitRepoName }}
            </v-chip>
          </div>
        </div>
      </v-card-text>
      <v-card-actions>
        <v-spacer />
        <v-btn variant="text" @click="emit('close')">
          Cancel
        </v-btn>
        <v-btn variant="flat" color="primary" @click="emit('confirm')">
          Enable All
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<style scoped>
.font-mono {
  font-family: monospace;
}
</style>
