// extension/ui-vue/src/components/dialogs/EditRepoDialog.vue
<script setup lang="ts">
/**
 * EditRepoDialog - Dialog for editing an existing Git repository.
 */
import { ref, computed, watch } from 'vue';

const props = defineProps<{
  modelValue: boolean;
  currentName: string;
  currentUrl: string;
  currentBranch?: string;
}>();

const emit = defineEmits<{
  (e: 'update:modelValue', value: boolean): void;
  (e: 'save', oldName: string, newName: string, url: string, branch?: string): void;
}>();

// Form state
const name = ref(props.currentName);
const url = ref(props.currentUrl);
const branch = ref(props.currentBranch || '');
const saving = ref(false);
const error = ref<string | null>(null);

// Reset form when dialog opens with new repo
watch(() => [props.modelValue, props.currentName, props.currentUrl, props.currentBranch], () => {
  if (props.modelValue) {
    name.value = props.currentName;
    url.value = props.currentUrl;
    branch.value = props.currentBranch || '';
    error.value = null;
  }
}, { immediate: true });

const hasChanges = computed(() =>
  name.value !== props.currentName ||
  url.value !== props.currentUrl ||
  branch.value !== (props.currentBranch || '')
);

function handleClose() {
  error.value = null;
  emit('update:modelValue', false);
}

async function handleSave() {
  if (!name.value || !url.value) return;

  saving.value = true;
  error.value = null;

  try {
    emit('save', props.currentName, name.value, url.value, branch.value || undefined);
    handleClose();
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'An error occurred';
  } finally {
    saving.value = false;
  }
}

// Expose method to set error from parent
function setError(errorMsg: string | null) {
  error.value = errorMsg;
  saving.value = false;
}

defineExpose({ setError });
</script>

<template>
  <v-dialog
    :model-value="modelValue"
    max-width="500"
    @update:model-value="emit('update:modelValue', $event)"
  >
    <v-card>
      <v-card-title>Edit Repository</v-card-title>
      <v-card-text>
        <v-alert
          v-if="error"
          type="error"
          closable
          class="mb-4"
          style="white-space: pre-wrap; font-family: monospace;"
          @click:close="error = null"
        >
          {{ error }}
        </v-alert>

        <div class="d-flex flex-column ga-3">
          <v-text-field
            v-model="name"
            label="Name"
            placeholder="my-app"
            hint="Unique name for this GitRepo resource"
            persistent-hint
            required
          />

          <v-text-field
            v-model="url"
            label="Repository URL"
            placeholder="https://github.com/org/repo"
            hint="Git repository URL (HTTPS)"
            persistent-hint
            required
          />

          <v-text-field
            v-model="branch"
            label="Branch"
            placeholder="main"
            hint="Branch to track (leave empty for default)"
            persistent-hint
          />

          <p class="text-body-2 text-medium-emphasis">
            Changing the repository URL will clear all selected paths. You will need to
            rediscover and select paths from the new repository.
          </p>
        </div>
      </v-card-text>
      <v-card-actions>
        <v-spacer />
        <v-btn variant="text" @click="handleClose">
          Cancel
        </v-btn>
        <v-btn
          variant="flat"
          color="primary"
          :disabled="!name || !url || !hasChanges || saving"
          :loading="saving"
          @click="handleSave"
        >
          {{ saving ? 'Saving...' : 'Save' }}
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

// extension/ui/src/components/EditRepoDialog.tsx
import { useState, useCallback, useEffect } from 'react';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import TextField from '@mui/material/TextField';
import Dialog from '@mui/material/Dialog';
import DialogTitle from '@mui/material/DialogTitle';
import DialogContent from '@mui/material/DialogContent';
import DialogActions from '@mui/material/DialogActions';
import Alert from '@mui/material/Alert';
import Typography from '@mui/material/Typography';

interface EditRepoDialogProps {
  open: boolean;
  currentName: string;
  currentUrl: string;
  currentBranch?: string;
  onClose: () => void;
  onSave: (oldName: string, newName: string, url: string, branch?: string) => Promise<void>;
}

export function EditRepoDialog({ open, currentName, currentUrl, currentBranch, onClose, onSave }: EditRepoDialogProps) {
  const [name, setName] = useState(currentName);
  const [url, setUrl] = useState(currentUrl);
  const [branch, setBranch] = useState(currentBranch || '');
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Reset form when dialog opens with new repo
  useEffect(() => {
    if (open) {
      setName(currentName);
      setUrl(currentUrl);
      setBranch(currentBranch || '');
      setError(null);
    }
  }, [open, currentName, currentUrl, currentBranch]);

  const handleClose = useCallback(() => {
    setError(null);
    onClose();
  }, [onClose]);

  const handleSave = useCallback(async () => {
    if (!name || !url) return;

    setSaving(true);
    setError(null);

    try {
      await onSave(currentName, name, url, branch || undefined);
      handleClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setSaving(false);
    }
  }, [currentName, name, url, branch, onSave, handleClose]);

  const hasChanges = name !== currentName || url !== currentUrl || branch !== (currentBranch || '');

  return (
    <Dialog
      open={open}
      onClose={handleClose}
      maxWidth="sm"
      fullWidth
    >
      <DialogTitle>Edit Repository</DialogTitle>
      <DialogContent>
        {error && (
          <Alert severity="error" sx={{ mb: 2, whiteSpace: 'pre-wrap', fontFamily: 'monospace' }} onClose={() => setError(null)}>
            {error}
          </Alert>
        )}
        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2, pt: 1 }}>
          <TextField
            label="Name"
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="my-app"
            helperText="Unique name for this GitRepo resource"
            required
            fullWidth
          />
          <TextField
            label="Repository URL"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            placeholder="https://github.com/org/repo"
            helperText="Git repository URL (HTTPS)"
            required
            fullWidth
          />
          <TextField
            label="Branch"
            value={branch}
            onChange={(e) => setBranch(e.target.value)}
            placeholder="main"
            helperText="Branch to track (leave empty for default)"
            fullWidth
          />
          <Typography variant="body2" color="text.secondary">
            Changing the repository URL will clear all selected paths. You will need to
            rediscover and select paths from the new repository.
          </Typography>
        </Box>
      </DialogContent>
      <DialogActions>
        <Button onClick={handleClose}>
          Cancel
        </Button>
        <Button
          onClick={handleSave}
          variant="contained"
          disabled={!name || !url || !hasChanges || saving}
        >
          {saving ? 'Saving...' : 'Save'}
        </Button>
      </DialogActions>
    </Dialog>
  );
}
