// extension/ui-vue/src/components/PathCheckbox.vue
<script setup lang="ts">
/**
 * PathCheckbox - Individual path checkbox with dependency info.
 *
 * Shows visual indicators for:
 * - Blocked paths (can't be selected due to missing dependencies)
 * - Protected paths (can't be deselected because other paths depend on them)
 * - Paths with dependencies (will auto-select other paths)
 */

import { computed } from 'vue';

interface BundleInfo {
  bundleName: string;
  path: string;
  gitRepoName: string;
}

interface PathInfo {
  path: string;
  name?: string;
}

interface DependencyResolution {
  canSelect: boolean;
  blockedBy: string[];
  willAutoSelect: BundleInfo[];
}

interface DeselectionInfo {
  canDeselect: boolean;
  requiredBy: BundleInfo[];
}

const props = defineProps<{
  pathInfo: PathInfo;
  isSelected: boolean;
  selectionInfo: DependencyResolution;
  deselectionInfo: DeselectionInfo | null;
  isUpdating: boolean;
}>();

const emit = defineEmits<{
  (e: 'toggle'): void;
  (e: 'showDependencyDialog'): void;
}>();

const isBlocked = computed(() => !props.selectionInfo.canSelect);
const isProtected = computed(() =>
  !!(props.isSelected && props.deselectionInfo && !props.deselectionInfo.canDeselect)
);
const hasDepsToSelect = computed(() => props.selectionInfo.willAutoSelect.length > 0);

// Build tooltip text
const tooltipText = computed(() => {
  if (isBlocked.value) {
    return `Blocked: requires ${props.selectionInfo.blockedBy.join(', ')} (not in any configured repository)`;
  }
  if (isProtected.value && props.deselectionInfo) {
    const requiredByNames = props.deselectionInfo.requiredBy.map(b => b.path).join(', ');
    return `Required by: ${requiredByNames}`;
  }
  if (hasDepsToSelect.value && !props.isSelected) {
    const depsToAdd = props.selectionInfo.willAutoSelect.map(b => b.path).join(', ');
    return `Will also enable: ${depsToAdd}`;
  }
  return '';
});

const isDisabled = computed(() =>
  props.isUpdating || isBlocked.value || isProtected.value
);

function handleChange() {
  if (isBlocked.value || isProtected.value) return;

  if (props.isSelected) {
    // Deselecting - simple toggle
    emit('toggle');
  } else if (hasDepsToSelect.value) {
    // Selecting with dependencies - show confirmation dialog
    emit('showDependencyDialog');
  } else {
    // Simple selection without dependencies
    emit('toggle');
  }
}
</script>

<template>
  <v-tooltip :text="tooltipText" location="top" :disabled="!tooltipText">
    <template #activator="{ props: tooltipProps }">
      <div v-bind="tooltipProps" class="path-checkbox-row">
        <v-checkbox
          :model-value="isSelected"
          :disabled="isDisabled"
          density="compact"
          hide-details
          class="path-checkbox"
          @update:model-value="handleChange"
        >
          <template v-if="isBlocked" #input>
            <v-icon icon="mdi-block-helper" color="error" size="small" />
          </template>
          <template v-else-if="isProtected && isSelected" #input>
            <v-icon icon="mdi-lock" color="info" size="small" />
          </template>
        </v-checkbox>

        <div class="path-label">
          <span class="path-text" :class="{ 'text-error': isBlocked, 'text-info': isProtected }">
            {{ pathInfo.path }}
          </span>

          <v-chip
            v-if="isProtected && deselectionInfo"
            size="x-small"
            color="info"
            variant="outlined"
            class="ml-1"
          >
            required by {{ deselectionInfo.requiredBy.length }}
          </v-chip>

          <v-chip
            v-if="hasDepsToSelect && !isSelected"
            size="x-small"
            color="warning"
            variant="outlined"
            class="ml-1"
          >
            +{{ selectionInfo.willAutoSelect.length }} deps
          </v-chip>

          <v-chip
            v-if="isBlocked"
            size="x-small"
            color="error"
            variant="outlined"
            class="ml-1"
          >
            blocked
          </v-chip>
        </div>
      </div>
    </template>
  </v-tooltip>
</template>

<style scoped>
.path-checkbox-row {
  display: flex;
  align-items: center;
  margin: -2px 0;
}

.path-checkbox {
  flex-shrink: 0;
}

.path-label {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 4px;
}

.path-text {
  font-family: monospace;
  font-size: 0.875rem;
}
</style>

// extension/ui/src/components/PathCheckbox.tsx
/**
 * PathCheckbox component - Individual path checkbox with dependency info.
 *
 * Extracted from GitRepoCard for better reusability and testability.
 */

import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import FormControlLabel from '@mui/material/FormControlLabel';
import Checkbox from '@mui/material/Checkbox';
import Chip from '@mui/material/Chip';
import Tooltip from '@mui/material/Tooltip';
import BlockIcon from '@mui/icons-material/Block';
import LockIcon from '@mui/icons-material/Lock';

import { BundleInfo, DependencyResolution } from '../types';
import { PathInfo } from '../utils';

/** Props for PathCheckbox component */
export interface PathCheckboxProps {
  /** Path information */
  pathInfo: PathInfo;
  /** Whether the path is currently selected */
  isSelected: boolean;
  /** Selection info from dependency resolver */
  selectionInfo: DependencyResolution;
  /** Deselection info (only provided when isSelected is true) */
  deselectionInfo: { canDeselect: boolean; requiredBy: BundleInfo[] } | null;
  /** Whether an update is in progress */
  isUpdating: boolean;
  /** Callback when the path is toggled */
  onToggle: () => void;
  /** Callback to show dependency confirmation dialog */
  onShowDependencyDialog: () => void;
}

/**
 * PathCheckbox - Displays a path with its selection state and dependency info.
 *
 * Shows visual indicators for:
 * - Blocked paths (can't be selected due to missing dependencies)
 * - Protected paths (can't be deselected because other paths depend on them)
 * - Paths with dependencies (will auto-select other paths)
 */
export function PathCheckbox({
  pathInfo,
  isSelected,
  selectionInfo,
  deselectionInfo,
  isUpdating,
  onToggle,
  onShowDependencyDialog,
}: PathCheckboxProps) {
  const isBlocked = !selectionInfo.canSelect;
  const isProtected = !!(isSelected && deselectionInfo && !deselectionInfo.canDeselect);
  const hasDepsToSelect = selectionInfo.willAutoSelect.length > 0;

  // Build tooltip text
  let tooltipText = '';
  if (isBlocked) {
    tooltipText = `Blocked: requires ${selectionInfo.blockedBy.join(', ')} (not in any configured repository)`;
  } else if (isProtected && deselectionInfo) {
    const requiredByNames = deselectionInfo.requiredBy.map((b) => b.path).join(', ');
    tooltipText = `Required by: ${requiredByNames}`;
  } else if (hasDepsToSelect && !isSelected) {
    const depsToAdd = selectionInfo.willAutoSelect.map((b) => b.path).join(', ');
    tooltipText = `Will also enable: ${depsToAdd}`;
  }

  const handleCheckboxChange = () => {
    if (isBlocked || isProtected) return;

    if (isSelected) {
      // Deselecting - simple toggle
      onToggle();
    } else if (hasDepsToSelect) {
      // Selecting with dependencies - show confirmation dialog
      onShowDependencyDialog();
    } else {
      // Simple selection without dependencies
      onToggle();
    }
  };

  return (
    <Tooltip
      title={tooltipText}
      placement="top"
      disableHoverListener={!tooltipText}
    >
      <FormControlLabel
        sx={{ my: -0.25 }}
        control={
          <Checkbox
            checked={isSelected}
            onChange={handleCheckboxChange}
            size="small"
            disabled={isUpdating || isBlocked || isProtected}
            sx={{ py: 0.5 }}
            icon={isBlocked ? <BlockIcon fontSize="small" color="error" /> : undefined}
            checkedIcon={isProtected ? <LockIcon fontSize="small" color="info" /> : undefined}
          />
        }
        label={
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, flexWrap: 'wrap' }}>
            <Typography
              variant="body2"
              sx={{
                fontFamily: 'monospace',
                color: isBlocked ? 'error.main' : isProtected ? 'info.main' : 'text.primary',
              }}
            >
              {pathInfo.path}
            </Typography>
            {isProtected && deselectionInfo && (
              <Chip
                size="small"
                label={`required by ${deselectionInfo.requiredBy.length}`}
                color="info"
                variant="outlined"
                sx={{ height: 18, fontSize: '0.7rem' }}
              />
            )}
            {hasDepsToSelect && !isSelected && (
              <Chip
                size="small"
                label={`+${selectionInfo.willAutoSelect.length} deps`}
                color="warning"
                variant="outlined"
                sx={{ height: 18, fontSize: '0.7rem' }}
              />
            )}
            {isBlocked && (
              <Chip
                size="small"
                label="blocked"
                color="error"
                variant="outlined"
                sx={{ height: 18, fontSize: '0.7rem' }}
              />
            )}
          </Box>
        }
      />
    </Tooltip>
  );
}

export default PathCheckbox;
